Repository osmlab/maproulette-python-client, pull requests merged in 2020-06, with the labels that each got.

#38 Add new properties
  maproulette/models/challenge.py
  maproulette/models/project.py
  maproulette/models/task.py
  tests/test_project_api.py
Labels: enhancement

#41 Add priority rule model
  docs/index.rst
  docs/usage/models/priority_rule.rst
  examples/create_challenge_from_model.py
  maproulette/__init__.py
  maproulette/models/__init__.py
  maproulette/models/challenge.py
  maproulette/models/priority_rule.py
Labels: enhancement

#45 Add task and challenge endpoints
  docs/usage/functionality.rst
  examples/add_tasks_to_challenge.py
  examples/add_user_list_to_project.py
  examples/add_user_to_project.py
  examples/challenge_examples.py
  examples/create_project_from_model.py
  examples/find_project.py
  examples/find_user_by_username.py
  examples/get_challenge_by_id.py
  examples/get_challenge_statistics_by_id.py
  examples/get_challenge_tasks.py
  examples/get_project_by_id.py
  examples/get_project_by_name.py
  examples/get_project_challenges.py
  examples/get_task_by_id.py
  examples/project_examples.py
  examples/task_examples.py
  examples/user_examples.py
  maproulette/api/challenge.py
  maproulette/api/configuration.py
  maproulette/api/maproulette_server.py
  maproulette/api/project.py
  maproulette/api/task.py
  maproulette/models/challenge.py
  tests/test_challenge_api.py
  tests/test_task_api.py
Labels: enhancement

#48 Fixed challenge model issue
  maproulette/models/challenge.py
Labels: bug

#47 Add changelog
  CHANGELOG.md
Labels: documentation
