Repository osmlab/maproulette-python-client, pull requests merged in 2020-04, with the labels that each got.

#18 [CI] PyPi publish on release
  .github/workflows/publish-to-test-pypi.yml
  setup.py
Labels: build/ci

#17 Build documentation using Sphinx
  .github/ISSUE_TEMPLATE.md
  .gitignore
  .travis.yml
  README.md
  docs/Makefile
  docs/conf.py
  docs/index.rst
  docs/make.bat
  docs/usage/functionality.rst
  docs/usage/getting_started.rst
  maproulette/__init__.py
  maproulette/api/api.py
  maproulette/api/configuration.py
  maproulette/api/maproulette_server.py
  maproulette/api/query_constants.py
  maproulette/models/challenge.py
  maproulette/models/project.py
  maproulette/models/task.py
  requirements.txt
  setup.py
  tox.ini
Labels: documentation

#19 Add tests for remaining methods
  tests/test_api.py
Labels: enhancement

#20 Added custom error class and removed/refactored endpoints affected by new MR release
  examples/create_challenge_from_model.py
  examples/get_project_children.py
  maproulette/api/api.py
  maproulette/api/errors.py
  maproulette/api/maproulette_server.py
  tests/test_api.py
  tests/test_server.py
Labels: enhancement

#23 Added docs for exceptions
  docs/index.rst
  docs/usage/exceptions.rst
  docs/usage/models/challenge.rst
  docs/usage/models/project.rst
  docs/usage/models/task.rst
  maproulette/api/errors.py
  maproulette/models/challenge.py
  maproulette/models/project.py
  maproulette/models/task.py
Labels: documentation
